---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-pod-create
  namespace: scenario-3
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "create", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-account-rolebinding
  namespace: scenario-3
subjects:
  - kind: ServiceAccount
    name: service-account-pod-create
roleRef:
  kind: Role
  name: role-pod-create
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-pod-create
  namespace: scenario-3
