apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: scenario-1
spec:
  nodeName: interdata.1721187715
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
  serviceAccount: default
